# high-level configuration for the full OBA run
run_options:
  target_name: test_target
  bands: ['b', 'lum']

# This list defines which OBA submodules to include in the analysis run
# NOTE: If not set, the default is to run all steps
modules:
  # - preprocessing
  # - cals
  # - masking
  # - background
  # - astrometry
  # - coadd
  # - detection
  - output
  # - cleanup

test:
  # realistic sims on the SuperBIT computer `hen`
  type: hen
  # sims produced by the ImSim module
  # test_type: imsim 

  # this tells the test prepper to skip compressing test images
  # if they are already present
  skip_existing: True

masking:
  types:
    # - cosmic_rays
    - satellites

astrometry:
  # can force the astrometry module to rerun the WCS solution even if
  # there is already a WCS in the image headers from the image checker
  rerun: True

  # the search radius about the target position, in deg
  search_radius: 10 # deg

cleanup:
  # NOTE: Will lose intermediate data products if you turn this on!
  clean_oba_dir: False
