# This list defines which OBA submodules to include in the analysis run
# NOTE: If not set, the default is to run all steps
modules:
  - preprocessing
  - cals
  - masking
  - background
  - astrometry
  - coadd
  - detection
  - cookiecutter

test:
  # realistic sims on the SuperBIT computer `hen`
  type: hen
  # sims produced by the ImSim module
  # test_type: imsim 

  # this tells the test prepper to skip compressing test images
  # if they are already present
  skip_existing: True

masking:
  types:
    - cosmic_rays
    - satellites
