target_name: 'Abell2813'
run_name: test_obj_wcs
master_seed: 72396
starting_roll: 30 # deg
rot_rate: 5 # deg / exp
exp_time: 300
n_exp: 2
#bands: ['u', 'b', 'g', 'r', 'lum', 'nir']
bands: ['vis']
ncores: 8

add_stars: True
add_galaxies: True
add_cluster: False

bkg_loc: 'L2'

# set if you want to specify the number instead of the default density
ngals: 100

star_stamp_size: 200

overwrite: True
fresh: False
vb: True