# Example master SExtractor config file

# Define the (unordered) list of SExtractor run types. The various options are:
# 
# 'det': Run SE on detection image for fiducial detections & positions
# 'coadd': Run SE on the single-band coadds
# 'exp': Run SE on all single-epoch exposures 
#
# If 'dual_mode' is True, then the 'coadd' and 'exp' runs will use the det
# coadd in dual-mode for detections
#
# defaults to running all three
# cat_types:
#   - det
#   - coadd
#   - exp

# set to True to have all detections be based upon a detection image
# (field 'det') and run SExtractor in dual mode
dual_mode: True

# NOTE: All filenames & paths are done relative to `config_dir` if provided.
#       This can also be passed as an arg to the run_sextractor.py script.
#       Example:
#config_dir: {PATH_TO_REPO}/superbit_lensing/detection/configs/

bands: [b, lum]
b: sb_sextractor_b.config
lum: sb_sextractor_lum.config
det: sb_sextractor_det.config

# SExtractor paramters to compute (uses SE default it not set)
parameters: sb_sextractor.param

# Which convolutional filter to use (uses SE default if not set)
filter: default.conv

# Which stellar classifier neural network to use (uses SE default if not set)
nnw: default.nnw
